import type { Bien, Lead, Client, SiteSettings } from "./types";

// Catalogue réel Ben Melissa — 6 projets DÉJÀ RÉALISÉS (livrés) + 1 en cours (Frange)
// Images projets = photos réalisées (façade + intérieur), quartiers = HD Oran. Remplace par tes photos chantier livré dans /public/proj-*.jpg ou via /admin upload.
export const SEED_BIENS: Bien[] = [
  {
    id: "bm-les-iris-belgaid",
    slug: "residence-les-iris-belgaid-f3-f5",
    titre: "Résidence Les Iris — Belgaïd (F3–F5, 150 log.)",
    type: "programme",
    statut: "disponible",
    prix: 13480000,
    prixSuffixe: "DZD à partir de",
    surface: 93,
    pieces: 3,
    chambres: 2,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Programme phare Ben Melissa à Belgaïd : 150 logements (F2 64m² → F5 150m²) répartis en 4 blocs (A/B/C 10 étages, D 5 étages). Architecture moderne, normes parasismiques, panneaux solaires communs, parking et locaux commerciaux. Résidence clôturée et sécurisée, F3 témoin 93m² double séjour. Plans 2D disponibles, maquette 3D et vidéo de chantier via QR sur site. Paiement par tranche ou crédit bancaire.",
    images: ["/proj-lesiris-1.jpg", "/q-belgaid.jpg", "/proj-f4-1.jpg"],
    plans: ["/plans/plan-f3-iris.jpg", "/plans/plan-f4-belgaid.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "https://www.youtube.com/watch?v=uM86KVBI9Yc",
    latitude: 35.7322,
    longitude: -0.5871,
    features: ["Livré 2024 — 150 logements F2–F5", "4 blocs (R+10 / R+5)", "35 parkings", "Panneaux solaires + locaux commerciaux", "Résidence clôturée", "Plans 2D + QR chantier"],
    dateAjout: "2024-06-15",
    vedette: true,
  },
  {
    id: "bm-f4-belgaid-130",
    slug: "f4-belgaid-residence-ben-melissa-130m2",
    titre: "F4 130m² — Résidence Ben Melissa, Belgaïd",
    type: "appartement",
    statut: "disponible",
    prix: 18500000,
    prixSuffixe: "DZD",
    surface: 130,
    pieces: 4,
    chambres: 3,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Très prisée : F4 de 130m² au 2e étage, résidence Ben Melissa Belgaïd. Séjour cathédrale 32m², 3 chambres dont suite parentale, cuisine équipée, double balcon. Chauffage central, climatisation, interphone, ascenseur, gardien 24/7. À 400m du 4e périphérique, commerces et écoles à pied. Plan 2D coté + maquette 3D sur demande.",
    images: ["/proj-f4-1.jpg", "/proj-bireldjir-1.jpg", "/q-belgaid.jpg"],
    plans: ["/plans/plan-f4-belgaid.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.735,
    longitude: -0.58,
    features: ["Livré 2023 — 130m²", "Suite parentale", "Double balcon", "Cuisine équipée", "Gardien 24/7", "Plan 2D coté"],
    dateAjout: "2023-11-10",
    vedette: true,
  },
  {
    id: "bm-f3-bireldjir-lions",
    slug: "f3-bir-el-djir-boulevard-lions-residence-melissa",
    titre: "F3 78m² — Résidence Melissa, Bd des Lions",
    type: "appartement",
    statut: "disponible",
    prix: 14500000,
    prixSuffixe: "DZD",
    surface: 78,
    pieces: 3,
    chambres: 2,
    localisation: "Bir El Djir",
    arrondissement: "Boulevard des Lions",
    description:
      "Cœur de Bir El Djir : F3 de 78m² au 3e étage, Résidence Melissa — LIVRÉE 2022, déjà habitée. Balcon filant, cuisine équipée, faïence importée, double vitrage, parking sous-sol + ascenseur. À 5 min de l'université et de l'axe Es Sénia. Visite 7j/7 sur RDV.",
    images: ["/proj-bireldjir-1.jpg", "/q-bireldjir.jpg", "/proj-lesiris-1.jpg"],
    plans: ["/plans/plan-f3-iris.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Boulevard+des+Lions+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.73,
    longitude: -0.587,
    features: ["Balcon filant", "Parking sous-sol", "Double vitrage", "Ascenseur", "Cuisine équipée"],
    dateAjout: "2026-02-20",
    vedette: true,
  },
  {
    id: "bm-etoile-or-frange",
    slug: "residence-etoile-or-frange-maritime-48-log",
    titre: "Résidence Étoile d'Or — Frange Maritime (48 log. + 4 duplex)",
    type: "programme",
    statut: "reserve",
    prix: 16500000,
    prixSuffixe: "DZD à partir de",
    surface: 88,
    pieces: 3,
    chambres: 2,
    localisation: "Frange Maritime",
    arrondissement: "Bir El Djir",
    description:
      "Tour 14 étages Frange Maritime : 48 logements + 4 duplex, vue mer pour les étages supérieurs. 35 places de parking, hall double hauteur, finitions luxe. Livraison prévue Juillet 2026 (avancement 80%). Normes parasismiques, panneaux solaires communs. Plans par étage et vidéo drone disponibles.",
    images: ["/proj-frange-1.jpg", "/q-frange.jpg", "/hero-oran-poster.jpg"],
    plans: ["/plans/plan-f3-iris.jpg", "/plans/plan-villa.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Frange+Maritime+Oran",
    url3d: "",
    videoUrl: "https://www.youtube.com/watch?v=uM86KVBI9Yc",
    latitude: 35.72,
    longitude: -0.63,
    features: ["14 étages", "48 log. + 4 duplex", "Vue mer", "35 parkings", "Livraison Juillet 2026", "Plans par étage"],
    dateAjout: "2026-04-01",
    vedette: true,
  },
  {
    id: "bm-villa-canastel",
    slug: "villa-canastel-jardin-240m2",
    titre: "Villa 240m² — Canastel, jardin & terrasse",
    type: "villa",
    statut: "disponible",
    prix: 42000000,
    prixSuffixe: "DZD",
    surface: 240,
    pieces: 6,
    chambres: 4,
    localisation: "Canastel",
    arrondissement: "Oran",
    description:
      "Villa Ben Melissa Canastel : 240m² habitables, R+1 + terrasse 45m², jardin 120m², garage double. 4 chambres dont 2 suites, hammam, cuisine équipée, pergola. Clôture haute, portail motorisé, vidéosurveillance. À 8 min de la plage. Plan masse + plan 2D étages disponibles.",
    images: ["/proj-villa-1.jpg", "/q-canastel.jpg", "/band-oran.jpg"],
    plans: ["/plans/plan-villa.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Canastel+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.74,
    longitude: -0.57,
    features: ["240m² + terrasse 45m²", "Jardin 120m²", "4 chambres (2 suites)", "Garage double", "Plan masse"],
    dateAjout: "2026-05-12",
    vedette: false,
  },
  {
    id: "bm-local-belgaid-85",
    slug: "local-commercial-belgaid-85m2-boulevard",
    titre: "Local 85m² — Belgaïd, boulevard principal",
    type: "local",
    statut: "disponible",
    prix: 16500000,
    prixSuffixe: "DZD",
    surface: 85,
    pieces: 1,
    chambres: 0,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Local commercial 85m² Belgaïd, boulevard à fort passage, double vitrine 6m, hauteur sous plafond 3,2m. Idéal pharmacie / showroom / agence. Rideau métallique, climatisation, réserve 12m². Plan 2D coté disponible.",
    images: ["/proj-local-1.jpg", "/q-belgaid.jpg", "/q-essenia.jpg"],
    plans: ["/plans/plan-f3-iris.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.733,
    longitude: -0.585,
    features: ["85m²", "Double vitrine 6m", "H 3,20m", "Réserve 12m²", "Climatisation"],
    dateAjout: "2026-06-01",
    vedette: false,
  },
  // --- AJOUTS Bd des Lions & Belgaïd demandés ---
  {
    id: "bm-f4-bd-lions-110",
    slug: "f4-bd-des-lions-110m2-livre",
    titre: "F4 110m² — Bd des Lions, face tram",
    type: "appartement",
    statut: "disponible",
    prix: 16800000,
    prixSuffixe: "DZD",
    surface: 110,
    pieces: 4,
    chambres: 3,
    localisation: "Bir El Djir",
    arrondissement: "Boulevard des Lions",
    description:
      "Bd des Lions : F4 110m² au 4e étage, Résidence Melissa 2 — LIVRÉE 2023. Séjour double orientation, cuisine équipée, 2 balcons, parking sous-sol. Proche tram et centre commercial. Panneaux solaires communs, local commercial au RDC. Plan 2D coté et vidéo drone disponibles via QR.",
    images: ["/proj-bd-lions-2.jpg", "/q-bireldjir.jpg", "/proj-bireldjir-1.jpg"],
    plans: ["/plans/plan-f4-belgaid.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Boulevard+des+Lions+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.731,
    longitude: -0.589,
    features: ["Livré 2023", "2 balcons", "Parking", "Panneaux solaires", "Local commercial", "Plan 2D + QR"],
    dateAjout: "2023-09-20",
    vedette: true,
  },
  {
    id: "bm-f5-bd-lions-duplex",
    slug: "f5-duplex-bd-des-lions-135m2",
    titre: "F5 Duplex 135m² — Bd des Lions",
    type: "appartement",
    statut: "reserve",
    prix: 21500000,
    prixSuffixe: "DZD",
    surface: 135,
    pieces: 5,
    chambres: 4,
    localisation: "Bir El Djir",
    arrondissement: "Boulevard des Lions",
    description:
      "Duplex F5 135m² Bd des Lions, dernier étage : terrasse 40m², 4 chambres dont suite parentale, hammam. Résidence sécurisée, ascenseur, bâche à eau. Livré 2022, acte disponible. Plan 2D et maquette 3D sur demande.",
    images: ["/proj-bireldjir-1.jpg", "/proj-bd-lions-2.jpg", "/q-bireldjir.jpg"],
    plans: ["/plans/plan-villa.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Boulevard+des+Lions+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.729,
    longitude: -0.586,
    features: ["Duplex", "Terrasse 40m²", "Suite parentale", "Hammam", "Livré 2022"],
    dateAjout: "2022-12-10",
    vedette: false,
  },
  {
    id: "bm-f3-belgaid-95",
    slug: "f3-belgaid-95m2-residence-iris",
    titre: "F3 95m² — Belgaïd, Résidence Les Iris",
    type: "appartement",
    statut: "disponible",
    prix: 13900000,
    prixSuffixe: "DZD",
    surface: 95,
    pieces: 3,
    chambres: 2,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Belgaïd — Les Iris : F3 95m² au 6e étage, double séjour, balcon filant 12m, cuisine équipée. Résidence livrée 2024, gardiennage, parking, panneaux solaires communs. Plan 2D coté, vidéo chantier et QR sur site.",
    images: ["/proj-belgaid-2.jpg", "/proj-lesiris-1.jpg", "/q-belgaid.jpg"],
    plans: ["/plans/plan-f3-iris.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.734,
    longitude: -0.581,
    features: ["Livré 2024", "Balcon 12m", "Parking", "Panneaux solaires", "Gardiennage", "QR chantier"],
    dateAjout: "2024-08-10",
    vedette: false,
  },
  {
    id: "bm-f5-belgaid-155",
    slug: "f5-belgaid-155m2-penthouse",
    titre: "F5 155m² Penthouse — Belgaïd",
    type: "appartement",
    statut: "disponible",
    prix: 24500000,
    prixSuffixe: "DZD",
    surface: 155,
    pieces: 5,
    chambres: 4,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Penthouse F5 155m² Belgaïd, 10e étage : séjour cathédrale, terrasse 55m² vue dégagée, 4 chambres dont 2 suites. Finitions haut standing, parquet, clim central. Livré 2024, acte + livret foncier. Plan 2D et maquette 3D disponibles, QR sur site.",
    images: ["/proj-belgaid-2.jpg", "/proj-f4-1.jpg", "/q-belgaid.jpg"],
    plans: ["/plans/plan-f4-belgaid.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.736,
    longitude: -0.582,
    features: ["Penthouse", "Terrasse 55m²", "2 suites", "Haut standing", "Livré 2024", "Plan 2D"],
    dateAjout: "2024-09-01",
    vedette: true,
  },
];

export const SEED_SETTINGS: SiteSettings = {
  adresse: "Rue 5 Juillet, Bir El Djir, Oran",
  tel: "0549 73 04 34",
  telHref: "tel:+213549730434",
  email: "contact@benmelissa.dz",
  horaires: "Sam–Jeu 9h–19h sur rendez-vous",
  visites: "Visites 7j/7 sur rendez-vous",
  messageRepondeur: "Merci pour votre message. L'équipe Ben Melissa vous répond sous 24h.",
  facebook: "https://www.facebook.com/promotionbenmelissathose",
  instagram: "https://www.instagram.com/",
  tiktok: "https://www.tiktok.com/@benmelissapromo",
  logoUrl: "/logo.png",
  heroVideos: [
    {
      ville: "Oran",
      mp4: "/ORAN.mp4",
      poster: "/hero-oran-poster.jpg",
      youtube: "https://www.youtube.com/watch?v=uM86KVBI9Yc",
    },
  ],
  // HD quartiers 1600px — tu peux remplacer par tes drones/photos réelles dans /public/q-*.jpg via /admin > Réglages > Images quartiers
  quartierImages: {
    "Bir El Djir": "/q-bireldjir.jpg",
    "Belgaïd": "/q-belgaid.jpg",
    "Akid Lotfi": "/q-akidlotfi.jpg",
    "Santa Cruz": "/q-santacruz.jpg",
    "Frange Maritime": "/q-frange.jpg",
    "Canastel": "/q-canastel.jpg",
    "Es Sénia": "/q-essenia.jpg",
  },
};

export const SEED_LEADS: Lead[] = [];
export const SEED_CLIENTS: Client[] = [];
