import type { Bien, Lead, Client, SiteSettings } from "./types";

// Catalogue réel Ben Melissa Promotion — 6 projets Oran (Bir El Djir / Belgaïd / Canastel / Frange maritime)
// Remplace les 3 démos Pexels. Chaque `plans` = Plan 2D (image HD ou PDF). L'admin n'a qu'à coller une URL dans /admin.
// Pour importer tes vrais projets : Admin > Import JSON — colle un tableau Bien[] ou CSV, ou édite ce fichier puis redéploie.
export const SEED_BIENS: Bien[] = [
  {
    id: "bm-les-iris-belgaid",
    slug: "residence-les-iris-belgaid-f3-f5",
    titre: "Résidence Les Iris — Belgaïd (F3–F5, 150 log.)",
    type: "programme",
    statut: "disponible",
    prix: 13480000,
    prixSuffixe: "DZD à partir de",
    surface: 93,
    pieces: 3,
    chambres: 2,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Programme phare Ben Melissa à Belgaïd : 150 logements (F2 64m² → F5 150m²) répartis en 4 blocs (A/B/C 10 étages, D 5 étages). Architecture moderne, locaux commerciaux + 35 parkings, résidence clôturée et sécurisée. F3 témoin 93m² : double séjour, cuisine équipée, balcon filant. Livraison par tranche, paiement échelonné ou crédit bancaire. Plans 2D et vidéo chantier disponibles — QR sur site.",
    images: ["/q-bireldjir.jpg", "/band-oran.jpg", "/srv-neuf.jpg"],
    // Plans : remplace par tes exports LayOut — /public/plans/f3-iris.jpg ou PDF. 1 URL par ligne dans /admin.
    plans: ["/srv-interieur.jpg", "/srv-neuf.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "https://www.youtube.com/watch?v=uM86KVBI9Yc",
    latitude: 35.7322,
    longitude: -0.5871,
    features: ["150 logements F2–F5", "4 blocs (R+10 / R+5)", "35 parkings", "Résidence clôturée", "Locaux commerciaux", "Plans 2D + QR chantier"],
    dateAjout: "2026-01-15",
    vedette: true,
  },
  {
    id: "bm-f4-belgaid-130",
    slug: "f4-belgaid-residence-ben-melissa-130m2",
    titre: "F4 130m² — Résidence Ben Melissa, Belgaïd",
    type: "appartement",
    statut: "disponible",
    prix: 18500000,
    prixSuffixe: "DZD",
    surface: 130,
    pieces: 4,
    chambres: 3,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Très prisée : F4 de 130m² au 2e étage, résidence Ben Melissa Belgaïd. Séjour cathédrale 32m², 3 chambres dont suite parentale, cuisine équipée, double balcon. Chauffage central, climatisation, interphone, ascenseur, gardien 24/7. À 400m du 4e périphérique, commerces et écoles à pied. Plan 2D coté + maquette 3D sur demande.",
    images: ["/q-bireldjir.jpg", "/srv-interieur.jpg", "/band-oran.jpg"],
    plans: ["/srv-interieur.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.735,
    longitude: -0.58,
    features: ["130m²", "Suite parentale", "Double balcon", "Cuisine équipée", "Gardien 24/7", "Plan 2D coté"],
    dateAjout: "2026-03-10",
    vedette: true,
  },
  {
    id: "bm-f3-bireldjir-lions",
    slug: "f3-bir-el-djir-boulevard-lions-residence-melissa",
    titre: "F3 78m² — Résidence Melissa, Bd des Lions",
    type: "appartement",
    statut: "disponible",
    prix: 14500000,
    prixSuffixe: "DZD",
    surface: 78,
    pieces: 3,
    chambres: 2,
    localisation: "Bir El Djir",
    arrondissement: "Boulevard des Lions",
    description:
      "Cœur de Bir El Djir : F3 de 78m² au 3e étage, Résidence Melissa. Balcon filant, cuisine équipée, faïence importée, double vitrage, parking sous-sol + ascenseur. À 5 min de l'université et de l'axe Es Sénia. Idéal primo-accédant. Visite 7j/7 sur RDV.",
    images: ["/q-akidlotfi.jpg", "/srv-interieur.jpg", "/q-bireldjir.jpg"],
    plans: ["/srv-neuf.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Boulevard+des+Lions+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.73,
    longitude: -0.587,
    features: ["Balcon filant", "Parking sous-sol", "Double vitrage", "Ascenseur", "Cuisine équipée"],
    dateAjout: "2026-02-20",
    vedette: true,
  },
  {
    id: "bm-etoile-or-frange",
    slug: "residence-etoile-or-frange-maritime-48-log",
    titre: "Résidence Étoile d'Or — Frange Maritime (48 log. + 4 duplex)",
    type: "programme",
    statut: "reserve",
    prix: 16500000,
    prixSuffixe: "DZD à partir de",
    surface: 88,
    pieces: 3,
    chambres: 2,
    localisation: "Frange Maritime",
    arrondissement: "Bir El Djir",
    description:
      "Tour 14 étages Frange Maritime : 48 logements + 4 duplex, vue mer pour les étages supérieurs. 35 places de parking, hall double hauteur, finitions luxe. Livraison prévue Juillet 2026 (avancement 80%). Normes parasismiques, panneaux solaires communs. Plans par étage et vidéo drone disponibles.",
    images: ["/q-santacruz.jpg", "/band-oran.jpg", "/hero-oran-poster.jpg"],
    plans: ["/srv-interieur.jpg", "/srv-neuf.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Frange+Maritime+Oran",
    url3d: "",
    videoUrl: "https://www.youtube.com/watch?v=uM86KVBI9Yc",
    latitude: 35.72,
    longitude: -0.63,
    features: ["14 étages", "48 log. + 4 duplex", "Vue mer", "35 parkings", "Livraison Juillet 2026", "Plans par étage"],
    dateAjout: "2026-04-01",
    vedette: true,
  },
  {
    id: "bm-villa-canastel",
    slug: "villa-canastel-jardin-240m2",
    titre: "Villa 240m² — Canastel, jardin & terrasse",
    type: "villa",
    statut: "disponible",
    prix: 42000000,
    prixSuffixe: "DZD",
    surface: 240,
    pieces: 6,
    chambres: 4,
    localisation: "Canastel",
    arrondissement: "Oran",
    description:
      "Villa Ben Melissa Canastel : 240m² habitables, R+1 + terrasse 45m², jardin 120m², garage double. 4 chambres dont 2 suites, hammam, cuisine équipée, pergola. Clôture haute, portail motorisé, vidéosurveillance. À 8 min de la plage. Plan masse + plan 2D étages disponibles.",
    images: ["/srv-interieur.jpg", "/q-akidlotfi.jpg", "/band-oran.jpg"],
    plans: ["/srv-neuf.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Canastel+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.74,
    longitude: -0.57,
    features: ["240m² + terrasse 45m²", "Jardin 120m²", "4 chambres (2 suites)", "Garage double", "Plan masse"],
    dateAjout: "2026-05-12",
    vedette: false,
  },
  {
    id: "bm-local-belgaid-85",
    slug: "local-commercial-belgaid-85m2-boulevard",
    titre: "Local 85m² — Belgaïd, boulevard principal",
    type: "local",
    statut: "disponible",
    prix: 16500000,
    prixSuffixe: "DZD",
    surface: 85,
    pieces: 1,
    chambres: 0,
    localisation: "Belgaïd",
    arrondissement: "Bir El Djir",
    description:
      "Local commercial 85m² Belgaïd, boulevard à fort passage, double vitrine 6m, hauteur sous plafond 3,2m. Idéal pharmacie / showroom / agence. Rideau métallique, climatisation, réserve 12m². Plan 2D coté disponible.",
    images: ["/q-bireldjir.jpg", "/srv-interieur.jpg", "/band-oran.jpg"],
    plans: ["/srv-interieur.jpg"],
    mapsUrl: "https://www.google.com/maps?q=Belgaïd+Bir+El+Djir+Oran",
    url3d: "",
    videoUrl: "",
    latitude: 35.733,
    longitude: -0.585,
    features: ["85m²", "Double vitrine 6m", "H 3,20m", "Réserve 12m²", "Climatisation"],
    dateAjout: "2026-06-01",
    vedette: false,
  },
];

export const SEED_SETTINGS: SiteSettings = {
  adresse: "Rue 5 Juillet, Bir El Djir, Oran",
  tel: "0549 73 04 34",
  telHref: "tel:+213549730434",
  email: "contact@benmelissa.dz",
  horaires: "Sam–Jeu 9h–19h sur rendez-vous",
  visites: "Visites 7j/7 sur rendez-vous",
  messageRepondeur: "Merci pour votre message. L'équipe Ben Melissa vous répond sous 24h.",
  facebook: "https://www.facebook.com/promotionbenmelissathose",
  instagram: "https://www.instagram.com/",
  tiktok: "https://www.tiktok.com/@benmelissapromo",
  logoUrl: "/logo.png",
  heroVideos: [
    {
      ville: "Oran",
      mp4: "/ORAN.mp4",
      poster: "/hero-oran-poster.jpg",
      youtube: "https://www.youtube.com/watch?v=uM86KVBI9Yc",
    },
  ],
};

export const SEED_LEADS: Lead[] = [];
export const SEED_CLIENTS: Client[] = [];
